sleep 1; echo "sleep 1 done"
sleep 2; echo "sleep 2 done"
sleep 3; echo "sleep 3 done"
sleep 4; echo "sleep 4 done"
sleep 5; echo "sleep 5 done"
sleep 6; echo "sleep 6 done"
sleep 7; echo "sleep 7 done"
sleep 8; echo "sleep 8 done"
