
message(STATUS "===================== Undefined variable  =========================")
message(STATUS "============== With negation")
message(STATUS "if(NOT \${UNDEFINED_VAR}) No quotes")
if(NOT ${UNDEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(NOT \"\${UNDEFINED_VAR}\") With quotes")
if(NOT "${UNDEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()


message(STATUS "============== Without negation")
message(STATUS "if(\${UNDEFINED_VAR}) No quotes")
if(${UNDEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(\"\${UNDEFINED_VAR}\") With quotes")
if("${UNDEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()


message(STATUS "\n")
message(STATUS "===================== SAME but with empty defined var =========================")
message(STATUS "============== With negation")
set(EMPTY_DEFINED_VAR "")
message(STATUS "if(NOT \${EMPTY_DEFINED_VAR}) No quotes")
if(NOT ${EMPTY_DEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(NOT \"\${EMPTY_DEFINED_VAR}\") With quotes")
if(NOT "${EMPTY_DEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()


message(STATUS "============== Without negation")
message(STATUS "if(\${EMPTY_DEFINED_VAR}) No quotes")
if(${EMPTY_DEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(\"\${EMPTY_DEFINED_VAR}\") With quotes")
if("${EMPTY_DEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "\n")
message(STATUS "===================== SAME but with non-empty defined var =========================")
message(STATUS "============== With negation")
set(NONEMPTY_DEFINED_VAR "some_value")
message(STATUS "if(NOT \${NONEMPTY_DEFINED_VAR}) No quotes")
if(NOT ${NONEMPTY_DEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(NOT \"\${NONEMPTY_DEFINED_VAR}\") With quotes")
if(NOT "${NONEMPTY_DEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "With the negation, quotes make a difference")

message(STATUS "============== Without negation")
message(STATUS "if(\${NONEMPTY_DEFINED_VAR}) No quotes")
if(${NONEMPTY_DEFINED_VAR})
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()

message(STATUS "if(\"\${NONEMPTY_DEFINED_VAR}\") With quotes")
if("${NONEMPTY_DEFINED_VAR}")
    message(STATUS "    inside IF")
else()
    message(STATUS "    inside ELSE")
endif()
