CFLAGS += -MMD
MAKE = make
CC = gcc
AR = ar
RM = rm -rf
$(obj): $(build_dir)/%.o : $(src_dir)/%.c
	$(call compile_info,$@,$<)
	$(CC) $(CFLAGS) -c $< -o $@
################################################################################
# Color codes for terminal output
################################################################################
red=9
green=10
yellow=11
blue=12
magenta=13
cyan=14
white=7
grey=8

cl=$(shell tput sgr0)

compile_colors=$(shell tput setab $(grey))$(shell tput setaf $(green))
define compile_info
	@echo "$(compile_colors)========== Compilation step : $2 -> $1 $(cl)"
endef

link_colors=$(shell tput setab $(grey))$(shell tput setaf $(magenta))
define link_info
	@echo "$(link_colors)========== Linking step : $2 -> $1 (linking with lib : $3)$(cl)"
endef

archive_colors=$(shell tput setab $(grey))$(shell tput setaf $(cyan))
define archive_info
	@echo "$(archive_colors)========== Archiving step : $2 -> $1$(cl)"
endef

cd_colors=$(shell tput setaf $(yellow))$(shell tput setab $(white)) asdf
define make_oter_dir
	@echo "$(cd_colors)=========================== making $2 in $1 ============================$(cl)"
	@cd $1; $(MAKE) $2
	@echo "$(cd_colors)====================== done making $2 in $1 ============================$(cl)"
endef






