CFLAGS += -MMD
MAKE = make
CC = gcc
AR = ar
RM = rm -rf
################################################################################
# Color codes for terminal output
################################################################################
c_green=tput setaf 3
c_magenta=tput setaf 4
c_yellow=tput setaf 5
c_none=tput sgr 0

$(obj): $(build_dir)/%.o : $(src_dir)/%.c
	@echo "$(c_magenta)Building object $@ from $<$(c_none)"
	$(CC) $(CFLAGS) -c $< -o $@




