#!/bin/bash

# assume command to be completed is salad
# and completions are generated by the executable
# ./_salad

COMP_WORDS=(salad -f ap)
COMP_CWORD=1 # The index of the word containing the cursor (the C is for cursor, not count)
COMP_LINE="salad -f ap"
COMP_POINT=${#COMP_LINE}
COMP_TYPE=9
COMP_KEY=$'\t'
oifs="$IFS"
IFS=$'\n'
candidates=($(./_salad salad ap -f))
IFS="$oifs"
for comp in "${candidates[@]}" ; do
    echo "$comp is one of the completion candidates"
done
