all:
	python3 comptest.py -f /opt/homebrew/share/bash-completion/bash_completion ~/.git-completion.bash -d $(PWD) "git commit --" --debug
	python3 comptest.py -f /opt/homebrew/share/bash-completion/bash_completion -d make --debug "make "
