#!/bin/sh

# Options : 
# -l where to search     : Default "*.c"
# -n Number of args      : Default "unknown"
# -d Look for definition : Default look for calls

# Arguments :
# function name
LOCATION="*.c"
option_l=false
option_n=false
option_d=false
while getopts "l:n:d" opt; do
	case "$opt" in
		l) LOCATION=$OPTARG
         option_l=true
			;;
		n) NARGS=$OPTARG
         option_n=true
			;;
		d)	option_d=true
         ;;
	esac
done
shift $((OPTIND - 1))

NARGS=$(($NARGS - 1))
FUNC=$1

# Regex pieces
CHARS="[a-zA-Z_\-]"
TYPE_RE="$CHARS\+"
ARG_RE="\(\ *\(\ *$CHARS\+\ \)\?\ *$CHARS\+\ *\**\ *$CHARS\+\ *\)"
PARAM_RE="\(\ *[-a-zA-Z0-9_\&\"%>\.]\+\ *\)"
# Doesnt work with string litterals because they can contain anything. 
# Maybe add a regex for string litterals, and have an actual param be a
# non-string litteral param or a string litteral.  But then there is still the
# problem of functions getting passed expressions as parameters.

# I think this script will end up being only usable reliably to find the
# definition of a function and calls will just have to be grep functionName with
# me sifting manually to distinguish what's a call and what's a trace message.
# I could put two greps together but then I lose line numbers

# Various regexes
DEF_RE_N="$TYPE_RE\ \+$FUNC\ *(\($ARG_RE,\)\{$NARGS\}$ARG_RE)" # Known number of args
DEF_RE="$TYPE_RE\ \+$FUNC\ *(\($ARG_RE,\)*$ARG_RE\?)" # Unknown number of args
CALL_RE_N="$FUNC\ *(\($PARAM_RE,\)\{$NARGS\}$PARAM_RE)"
CALL_RE="$FUNC\ *(\($PARAM_RE,\)*$PARAM_RE\?)"
VARARGS_DEF_REGEX="$TYPE_RE\ \+$FUNC\ *(\($ARG_RE,\)*\ *\.\.\.\ *)"
grep "$VARARGS_DEF_REGEX" $LOCATION --color -n

# Echo back information
echo "FUNCTION: $FUNC"

if [[ $option_n = true ]];then
   echo "NARGS   : $(($NARGS + 1))"
   DEF_RE=$DEF_RE_N
   CALL_RE=$CALL_RE_N
else
   echo "NARGS   : Unkonwn"
fi

if [[ $option_d = true ]];then
   echo "Looking for definition"
   RE=$DEF_RE
else
   echo "Looking for calls"
   RE=$CALL_RE
fi

echo "$RE"
grep "$RE" $LOCATION --color -n
