#!/usr/bin/env bash
#
# Found out about this trick from reading a configure script generated by
# autotools:
#
# This is just to confirm that it works.  The probably do it like this to avoid
# a fork but nowadays, we're good on that front.
#
# Plus if my variable is a list, I probably want to preserve list elements
# that have spaces so I would be using arrays.
#

var_containing_newlines_and_spaces="a
b
c    d
e       f"

set x ${var_containing_newlines_and_spaces}
shift
var_without_newlines_or_multiple_spaces=$*

echo "${var_without_newlines_or_multiple_spaces}"

# Other technique which requires fork:
#
var_without_newlines_or_multiple_spaces=$(echo ${var_containing_newlines_and_spaces})
echo "${var_without_newlines_or_multiple_spaces}"


